import pandas as pd
import ta

# --- EXISTING FUNCTION (Kept intact for your other screeners) ---
def add_indicators(df):
    df["50DMA"] = df["Close"].rolling(50).mean()
    df["200DMA"] = df["Close"].rolling(200).mean()
    df["RSI"] = ta.momentum.RSIIndicator(df["Close"], window=14).rsi()
    df["AvgVolume"] = df["Volume"].rolling(20).mean()
    return df

# --- NEW FUNCTION (For the new EMA/RSI Pullback Strategy) ---
def calculate_ema_pullback_indicators(df):
    """Calculates indicators specifically for the EMA Pullback Screener."""
    df_calc = df.copy() # Prevents modifying the original raw dataframe
    
    # EMAs using the 'ta' library trend module
    df_calc['EMA_200'] = ta.trend.EMAIndicator(df_calc['Close'], window=200).ema_indicator()
    df_calc['EMA_50'] = ta.trend.EMAIndicator(df_calc['Close'], window=50).ema_indicator()
    df_calc['EMA_21'] = ta.trend.EMAIndicator(df_calc['Close'], window=21).ema_indicator()
    
    # RSI using the 'ta' library momentum module
    df_calc['RSI_14'] = ta.momentum.RSIIndicator(df_calc['Close'], window=14).rsi()
    
    # Volume MA (Simple Moving Average)
    df_calc['Vol_MA_20'] = df_calc['Volume'].rolling(window=20).mean()
    
    # ATR using the 'ta' library volatility module
    df_calc['ATR_14'] = ta.volatility.AverageTrueRange(
        high=df_calc['High'], 
        low=df_calc['Low'], 
        close=df_calc['Close'], 
        window=14
    ).average_true_range()
    
    # Clean up NaNs generated by the 200-day window
    return df_calc.dropna()
